# Generated by Django 4.2.8 on 2023-12-15 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aplicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="", max_length=256)),
                ("url", models.CharField(default="", max_length=1024)),
                ("apelido", models.CharField(max_length=512)),
                ("descricao", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("erro", models.CharField(default="", max_length=512)),
                ("traceback", models.TextField()),
                ("nivel", models.IntegerField(default=0)),
                ("data_hora", models.DateField(default=django.utils.timezone.now)),
                (
                    "aplicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.aplicacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-data_hora"],
            },
        ),
    ]
