# Generated by Django 4.2.8 on 2023-12-15 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aplicacao",
            name="ide",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
